ThatConference/that-api-members

.vscode/settings.json
package-lock.json
package.json
src/graphql/index.js
src/index.js

Story details: https://app.clubhouse.io/thatconference/story/1506

Add sentry

---

src/graphql/resolvers/queries/index.js
src/graphql/resolvers/queries/members.js
src/graphql/typeDefs/queries/members.graphql
src/graphql/typeDefs/schema.graphql

Story details: https://app.clubhouse.io/thatconference/story/1513

create the base schema across all services

---

package-lock.json
package.json
src/index.js

Adds response time and adds the express cors handler
closes issue #5

adds better cors handing

---

.github/workflows/pushMasterCi.yml

Includes slack notification update

add post build event [ch2257]

---

package-lock.json
package.json
src/dataSources/cloudFirestore/member.js
src/graphql/directives/index.js
src/graphql/resolvers/queries/members.js
src/graphql/typeDefs/dataTypes/profile.graphql
src/graphql/typeDefs/directives.graphql
src/graphql/typeDefs/queries/members.graphql

* enforces slug to be lower on creation
* adds a query to check it a slug is taken.
* enforces check on profile creation as well.

enables slug lowerCase and is slug taken

---

.github/workflows/pushMasterCi.yml
src/graphql/resolvers/mutations/member.js
src/graphql/resolvers/mutations/members.js

Create and update action transactional email templates added plus version format update.

add create and update tranaction email template sends

---

src/dataSources/cloudFirestore/member.js
src/events/user.js
src/graphql/resolvers/mutations/member.js
src/graphql/resolvers/mutations/members.js
src/graphql/typeDefs/dataTypes/profileInput.graphql
src/index.js

* fixes new account creation bug where it wasn't getting created
* removes required fields on input
* user notifications are now via an event system

event driven emails

---

src/graphql/index.js

* fixes dataloader order reference

updating dataloader to maintain order

---

src/dataSources/cloudFirestore/member.js

fix createdAt cursor

---

src/dataSources/apis/tito.js

fix as a result of poor testing.

stringify body before sending

---

src/events/user.js

found from Sentry issue, [774f4760551b4e308b21d29710632a95](https://sentry.io/organizations/that-conference/issues/1871927601/events/774f4760551b4e308b21d29710632a95/)

fix error caused by deconstructing value

---

src/dataSources/cloudFirestore/session.js
src/graphql/resolvers/queries/publicProfile.js
src/lib/slackNotifications.js

Add simple session resolver for PublicProfile to return accepted sessions. No paging, no past/future/etc.
fixes #72

Add simple session resolver for PublicProfile

---

package.json
src/dataSources/cloudFirestore/sharedProfile.js
src/graphql/resolvers/mutations/index.js
src/graphql/resolvers/mutations/member.js
src/graphql/resolvers/mutations/profiles.js
src/graphql/resolvers/mutations/sharedProfile.js
src/graphql/resolvers/queries/index.js
src/graphql/resolvers/queries/members.js
src/graphql/resolvers/queries/profiles.js
src/graphql/typeDefs/dataTypes/sharedProfile.graphql
src/graphql/typeDefs/dataTypes/sharedProfileInput.graphql
src/graphql/typeDefs/mutations/member.graphql
src/graphql/typeDefs/mutations/profiles.graphql
src/graphql/typeDefs/mutations/sharedProfile.graphql
src/graphql/typeDefs/queries/members.graphql
src/graphql/typeDefs/queries/profiles.graphql

Returns profile/shared  or THAT profile information
Federation reference of type SharedProfile
Query: members/profiles/shared
Mutation: 
- members/member/profiles/shared/create
- members/member/profiles/shared/update
- members/member/profiles/shared/delete

Adds CRUD for SharedProfile type. 

---

package.json
src/graphql/resolvers/queries/profile.js
src/graphql/resolvers/queries/publicProfile.js
src/graphql/typeDefs/dataTypes/extended-asset.graphql
src/graphql/typeDefs/dataTypes/profile.graphql
src/graphql/typeDefs/dataTypes/publicProfile.graphql

Asset type added to Profile and PublicProfile

Adds asset reference to profile types

---

package.json
src/graphql/resolvers/mutations/members.js

add graphCdn event emitter to profile create

---

package.json
src/dataSources/cloudFirestore/member.js
src/graphql/resolvers/mutations/adminMember.js
src/graphql/typeDefs/mutations/adminMember.graphql

v2.11.0
implement admin mutation for member update and deactivate

implement admin mutation member update, deactivate

---

package-lock.json
package.json
src/lib/activeCampaign.js
src/lib/activeCampaignActions.js

stringify deep objects for Sentry. Bring in patched that-api

---

package.json
src/graphql/resolvers/queries/profile.js
src/graphql/typeDefs/dataTypes/notificationPreferences.graphql
src/graphql/typeDefs/dataTypes/notificationPreferencesInput.graphql
src/graphql/typeDefs/dataTypes/profile.graphql
src/graphql/typeDefs/dataTypes/profileInput.graphql

v.3.4.0
Adds notification preferences
adds sharedProfile under profile type
no package updates

feat: Adds notification preferences

---

package.json
src/graphql/resolvers/queries/profile.js
src/graphql/typeDefs/dataTypes/notificationPreferences.graphql
src/graphql/typeDefs/dataTypes/notificationPreferencesInput.graphql

feat: change meetThat to meetThatCamper

---

package.json
src/dataSources/cloudFirestore/member.js

v3.5.1
Fix notificationPreferences updates.
allows individual fields of notificationPreferences to be updated

fix: allows individual fields of notificationPreferences to be updated
